### ISSUE TITLE
Getting an error when i start up the plugin.

### ISSUE THREAD

**Issue by rugter100** [Chafficui/MyTrip#5]
I have tried multiple versions and it keeps happening. Mabye it is a conflict with any of my other plugins?

Error code:
```
[21:23:24] [Server thread/ERROR]: Error occurred while enabling MyTrip v0.4.4 (Is it up to date?)
--
java.lang.NullPointerException: null
at de.chaffic.MyTrip.Main.createItems(Main.java:527) ~[?:?]
at de.chaffic.MyTrip.Main.onEnable(Main.java:107) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
The server is under a bungee but i dont think that should be an issue for the plugin?

**Comment by Chafficui** [comment]
Hello. Which serverversion do you use?

**Comment by rugter100** [comment]
I am using paperspigot 243 which is for version 1.14.4

**Comment by Chafficui** [comment]
Try to use latest pre-release (you can download it at GitHub, Bukkit or Songoda). It may be that the error is fixed there, but I can't promise.

**Comment by Chafficui** [comment]
Ich schließe das Ticket und sehe es als gelöst an, wenn du in den nächsten 24 Stunden nicht antwortest :)
